swagger: "2.0"
info:
  description: |
    Produktanbieter-Darlehensdaten API
    Benutzt werden JSON Datentypen, siehe http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf
  title: PADD API
  version: 0.0.1
schemes:
- http
produces:
- application/json
consumes:
- application/json

# Pfade und Ressourcen
paths:
  /darlehensdaten:
    post:
      summary: Anfrage von Darlehensdaten
      description: TBD
      operationId: postDarlehensdatenAnfrage
      parameters:
        - name: anfrage
          in: body
          required: true
          schema:
            $ref: '#/definitions/DarlehensdatenAnfrage'

      responses:
        200:
          description: Erfolgreiche Antwort
          schema:
            $ref: '#/definitions/DarlehensdatenAntwort'
        default:
          description: unspezifizierter Fehler

# Objektdefinitionen
definitions:
  DarlehensId:
    type: string
    description: |
      Eindeutige ID des Darlehens beim Produktanbieter, z.B. Darlehensnummer, Kontonummer oder IBAN.
      Kann Buchstaben, Zahlen oder andere Sonderzeichen enthalten.

  PartnerId:
    type: string
    description: |
      Die ID eines Partners im Europace2 System

  Partner:
    type: object
    properties:
      vorname:
        type: string
      nachname:
        type: string
      email:
        type: string
      partnerId:
        $ref: '#/definitions/PartnerId'

  Antragsteller:
    description: Daten eines Antragsteller
    type: object
    properties:
      vorname:
        type: string
      nachname:
        type: string
      geburtsdatum:
        description: Geburtsdatum nach RFC3339
        type: string
        format: date
        example: 1973-03-29
      anschrift:
        $ref: "#/definitions/Postadresse"

  Finanzierungsobjekt:
    description: Daten zur bestehenden Immobilie
    properties:
      adresse:
        $ref: "#/definitions/Postadresse"

  DarlehensArt:
    description: Definiert die Art des Finanzierungsbausteins.
    type: string
    enum:
      - IMMOBILIENDARLEHEN
      - BAUSPARDARLEHEN
      - FOERDERDARLEHEN
      - SONSTIGES_DARLEHEN

  Euro:
    description: |
      JSON Number type ohne Währungssymbol, siehe http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf.
      Vorkomma ist der Eurobetrag und zwei Nachkommastellen - Cents 0-99.
      Beispiele: 50000 oder 1234.56
    type: number
    format: Eurobetrag

  Prozent:
    description: |
      JSON Number type ohne Prozentzeichen, siehe http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf.
      Prozent ist 100 basierend.
      Beispiele: 60 oder 2.562
    type: number
    format: Prozentsatz

  BestehendesDarlehen:
    properties:
      darlehensKontonummer:
        description: IBAN, Konto- oder Unterkontonummer des Produktanbieters.
        type: string
      darlehensArt:
        $ref: '#/definitions/DarlehensArt'
      urspruenglicherDarlehensBetrag:
        $ref: '#/definitions/Euro'
      rateMonatlich:
        $ref: '#/definitions/Euro'
      zinsBindungBis:
        description: Zinsbindungsende, Datum nach RFC3339
        type: string
        format: date
        example: 2020-12-31
      abzuloesendeRestschuld:
        $ref: '#/definitions/Euro'
      sollZins:
        $ref: '#/definitions/Prozent'

  DarlehensdatenAnfrage:
    type: object
    properties:
      hauptkontonummer:
        $ref: '#/definitions/DarlehensId'
      bestehendeDarlehen:
        type: array
        items:
          $ref: '#/definitions/BestehendesDarlehen'
      kundenBetreuer:
        $ref: '#/definitions/Partner'
      bearbeiter:
        $ref: '#/definitions/Partner'
      antragsteller:
        type: array
        items:
          $ref: '#/definitions/Antragsteller'
      finanzierungsobjekt:
        $ref: '#/definitions/Finanzierungsobjekt'

  DarlehensdatenAntwort:
    type: object
    properties:
      hauptkontonummer:
        $ref: '#/definitions/DarlehensId'
      bestehendeDarlehen:
        type: array
        items:
          $ref: '#/definitions/BestehendesDarlehen'

  Postadresse:
    type: object
    properties:
      strasse:
        type: string
      hausnummer:
        type: string
      postleitzahl:
        type: string
      ort:
        type: string
