swagger: "2.0"
info:
  description: |
    Produktanbieter-Darlehensdaten API
    Benutzt werden JSON Datentypen, siehe http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf
  title: PADD API
  version: 0.0.1
schemes:
- http
produces:
- application/json
consumes:
- application/json

# Pfade und Ressourcen
paths:
  /darlehensdaten:
    post:
      summary: Anfrage von Darlehensdaten
      description: TBD
      operationId: postDarlehensdatenAnfrage
      parameters:
        - name: anfrage
          in: body
          required: true
          schema:
            $ref: '#/definitions/DarlehensdatenAnfrage'

      responses:
        200:
          description: Erfolgreiche Antwort
          schema:
            $ref: '#/definitions/DarlehensdatenAntwort'
        default:
          description: unspezifizierter Fehler

# Objektdefinitionen
definitions:
  DarlehensId:
    type: string
    description: |
      Eindeutige ID des Darlehens beim Produktanbieter, z.B. Darlehensnummer, Kontonummer oder IBAN.
      Kann Buchstaben, Zahlen oder andere Sonderzeichen enthalten.

  PartnerId:
    type: string
    description: |
      Die ID eines Partners im Europace2 System

  Partner:
    type: object
    properties:
      partnerId:
        $ref: '#/definitions/PartnerId'

  Antragsteller:
    description: Daten eines Antragsteller
    type: object
    properties:
      id:
        description: Eindeutiger Identifier des Antragstellers im Europace 2 Systems
        type: string
      vorname:
        type: string
      nachname:
        type: string
      geburtsdatum:
        description: Geburtsdatum nach RFC3339
        type: string
        format: date
        example: 1973-03-29

  Immobilie:
    description: Daten zur bestehenden Immobilie
    properties:
      plz:
        type: string
      ort:
        type: string
      strasse:
        type: string

  DarlehensArt:
    description: Definiert die Art des Finanzierungsbausteins.
    type: string
    enum:
      - Annuit채tendarlehen
      - KfW
      - Forward
      - Prolongation

  Euro:
    description: |
      JSON Number type ohne W채hrungssymbol, siehe http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf.
      Vorkomma ist der Eurobetrag und zwei Nachkommastellen - Cents 0-99.
      Beispiele: 50000 oder 1234.56
    type: number
    format: Eurobetrag

  Prozent:
    description: |
      JSON Number type ohne Prozentzeichen, siehe http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf.
      Prozent ist 100 basierend.
      Beispiele: 60 oder 2.562
    type: number
    format: Prozentsatz

  Finanzierungsbaustein:
    description: Repr채sentanz eines Teils der Gesamtfinanzierung.
    properties:
      kontonummer:
        description: IBAN, Konto- oder Unterkontonummer des Produktanbieters.
        type: string
      darlehensArt:
        $ref: '#/definitions/DarlehensArt'
      darlehensBetrag: # Urspr체nglicher Betrag des Darlehens.
        $ref: '#/definitions/Euro'
      rateMonatlich:
        $ref: '#/definitions/Euro'
      zinsbindungsende:
        description: Zinsbindungsende, Datum nach RFC3339
        type: string
        format: date
        example: 2020-12-31
      restschuldZinsbindungsende:
        $ref: '#/definitions/Euro'
      sollZins:
        $ref: '#/definitions/Prozent'

  DarlehensdatenAnfrage:
    type: object
    properties:
      darlehensId:
        $ref: '#/definitions/DarlehensId'
      kundenBetreuer:
        $ref: '#/definitions/Partner'
      bearbeiter:
        $ref: '#/definitions/Partner'
      antragsteller:
        type: array
        items:
          $ref: '#/definitions/Antragsteller'
      immobilie:
        $ref: '#/definitions/Immobilie'

  DarlehensdatenAntwort:
    type: object
    properties:
      darlehensId:
        $ref: '#/definitions/DarlehensId'
      bausteine:
        type: array
        items:
          $ref: '#/definitions/Finanzierungsbaustein'

